// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
..............................
..............................
..............................
..............................
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
..............................
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
........ffffffffffffff........
..............................
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
........dddddddddddddd........
..............................
..............................
..............................
..............................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
